### ISSUE TITLE
Any way to do separate compilation of device code?

### ISSUE THREAD

**Issue by rnburn** [liuliu/rules_cuda#3]
Is there any way to set up separate compilation of device code with this project and nvcc?

Here's an example from the nvidia docs: https://developer.nvidia.com/blog/separate-compilation-linking-cuda-device-code/

It's not clear to me how to make it work since it uses nvcc as the linker because it needs to recognize device code embedded in the object files.

**Comment by liuliu** [comment]
Yeah, probably need to modify `cuda_library` to do `prelink` (that's the terminology for linking multiple *.o files into one *.o file) and after that, just treat the resulting *.a as normal library (hence, will not pass `-x cuda` to the linker, and that will trigger ordinary linker rather than nvcc from https://github.com/liuliu/rules_cuda/blob/main/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc.tpl). https://github.com/liuliu/rules_cuda/blob/main/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc.tpl#L275

**Comment by liuliu** [comment]
The `cuda_library` in this rules_cuda is implemented as a macro, hence, it is not obvious how to add `prelink` support easily.

**Comment by rnburn** [comment]
Added support in #4
